# Genetic algorithm hyperparameters
  target_image    : "images/Checkerboard_pattern.png"
  checkpoint_path : ""
  reduce_factor   : 8
  generations     : 5000000
  spatial_depth   : 8
  scale_depth     : 36
  pop_size        : 32
  parent_k        : 16
  num_elites      : 1
  mut_rate        : 0.1
  mut_scale       : 0.01
  analyze_every   : 1000